export default {
  products: [
    {
      _id: "1",
      name: "Juhu Beach",
      category: "Beach",
      image: "/images/JuhuBeach.jpeg",
      price: 250,
      brand: " KD Travellers",
      rating: 4.5,
      numReviews: 10,
      countInStock: 30,
    },
    {
      _id: "2",
      name: "Versova Beach",
      category: "Beach",
      image: "/images/varsovaBeach.jpg",
      price: 499,
      brand: " Mayur Agency",
      rating: 4.2,
      numReviews: 5,
      countInStock: 20,
    },
    {
      _id: "3",
      name: "Vihar Lake",
      category: "Lake",
      image: "/images/viharLake.jpg",
      price: 499,
      brand: " Deva Tours",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "4",
      name: "Powai Lake",
      category: "Lake",
      image: "/images/powaiLake.jpg",
      price: 250,
      brand: " Hemanth Travells",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "5",
      name: "Nanda Devi",
      category: "Mountains",
      image: "/images/NandaDevi.jpg",
      price: 3000,
      brand: " KD Travellers",
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: "6",
      name: "Shimla",
      category: "Mountains",
      image: "/images/Shimla.jpg",
      price: 9999,
      brand: " Mayur Agency",
      rating: 4.2,
      numReviews: 5,
      countInStock: 20,
    },
    {
      _id: "7",
      name: "Taj Mahel",
      category: "Historical",
      image: "/images/Taj.jpg",
      price: 4990,
      brand: " Deva Tours",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
    {
      _id: "8",
      name: "Red Fort",
      category: "Historical",
      image: "/images/redfort.jpg",
      price: 2500,
      brand: " Hemanth Travells",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
    },
  ],
};
